services:
  # SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_mbk
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "a123456789A!"
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver_data:/var/opt/mssql  # Map the local ./data folder for persistence
    networks:
      - microservices-network

  # User Service
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver_mbk:1433;databaseName=userdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: a123456789A!
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - sqlserver
    networks:
      - microservices-network

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
    networks:
      - microservices-network

# Defining Docker networking to enable communication between containers
networks:
  microservices-network:
    driver: bridge

