services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_mbk
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=a12345678A!
      - MSSQL_PID=Express
    volumes:
      - ./sqlserver_data:/var/opt/mssql
    restart: always
