services:
  # SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_kone
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "a123456789A!"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql  # Mappa la cartella locale ./data per la persistenza
    networks:
      - microservices-network

  # User Service
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver_kone:1433;databaseName=userdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: a123456789A!
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - sqlserver
    networks:
      - microservices-network

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
    networks:
      - microservices-network

# Definizione della rete Docker per consentire la comunicazione tra i container
networks:
  microservices-network:
    driver: bridge

